image: gcr.io/ajensen-1993/stocker
cronJob:
  schedule: "0 1 * * 0"
job: false
config:
  timezone: America/Chicago
  exchange: US
  startDate: null
  endDateDate: null
  dataSourceName: postgres://pgdb-svc:5432/stocker?sslmode=disable
  dbConnPoolConfig:
    maxConnLifetime: 24h
    maxConnIdleTime: 1h
    healthCheckPeriod: 1m
    minConns: 1
    maxConns: 8
  resolution: D
  migrationSourceUrl: file:///var/migrate