image:
  repository: "gcr.io/ajensen-1993/stocker"
  pullPolicy: ""
  tag: ""
  digest: ""
schedule: "0 1 * * 0"
config:
  timezone: America/Chicago
  exchange: US
  startDate: null
  endDateDate: null
  dataSourceName: "postgres://pgdb-svc:5432/stocker?sslmode=disable"
  db_conn_pool_config:
    max_conn_lifetime: 24h
    max_conn_idle_time: 1h
    health_check_period": 1m
    min_conns: 1,
    max_conns: 8
  resolution: D
  migration_source_url: "file:///var/migrate"