apiVersion: v1
kind: Secret
metadata:
  name: stocker-db-secret
type: Opaque
data:
  stocker-db-secret.json: ewogICJ1c2VybmFtZSI6ICJzdG9ja2VyIiwKICAicGFzc3dvcmQiOiAic3RvY2tlciIKfQ==  #this is base64 for stocker/stocker

