{{- define "jobSpec" -}}
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: OnFailure
      initContainers:
        - name: stocker-init
          image: "{{ .Values.image }}"
          imagePullPolicy: IfNotPresent
          command:
            - /bin/app
            - migrate
            - up
          volumeMounts:
            - mountPath: /etc/config
              name: stocker-config-volume
            - name: k8info-init
              mountPath: /etc/k8info
      containers:
        - name: stocker
          image: "{{ .Values.image }}"
          imagePullPolicy: IfNotPresent
          command:
            - /bin/app
            - etl
          volumeMounts:
            - mountPath: /etc/config
              name: stocker-config-volume
            - name: k8info
              mountPath: /etc/k8info
      volumes:
        - name: stocker-config-volume
          projected:
            sources:
              - configMap:
                  name: stocker-config-cm
              - secret:
                  name: stocker-api-secret
              - secret:
                  name: stocker-db-secret
        - name: stocker-init-config-volume
          projected:
            sources:
              - configMap:
                  name: stocker-config-cm
              - secret:
                  name: stocker-db-secret
        - name: k8info
          projected:
            sources:
              - downwardAPI:
                  items:
                    - path: pod_name
                      fieldRef:
                        fieldPath: metadata.name
                    - path: pod_namespace
                      fieldRef:
                        fieldPath: metadata.namespace
                    - path: pod_labels
                      fieldRef:
                        fieldPath: metadata.labels
              - configMap:
                  name: k8-cluster-info-cm
              - configMap:
                  name: stocker-container-name-cm
        - name: k8info-init
          projected:
            sources:
              - downwardAPI:
                  items:
                    - path: pod_name
                      fieldRef:
                        fieldPath: metadata.name
                    - path: pod_namespace
                      fieldRef:
                        fieldPath: metadata.namespace
                    - path: pod_labels
                      fieldRef:
                        fieldPath: metadata.labels
              - configMap:
                  name: k8-cluster-info-cm
              - configMap:
                  name: stocker-init-container-name-cm
{{- end -}}