apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Chart.Name }}-cronjob
spec:
  schedule: "{{ .Values.schedule }}"
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: {{ .Chart.Name }}
            image: "{{ .Values.image.repository }}{{ with .Values.image.tag }}:{{ . }}{{ end }}{{ with .Values.image.digest }}@{{ . }}{{ end }}"
            imagePullPolicy: {{ default "IfNotPresent" .Values.image.pullPolicy }}
            command:
              - /bin/app
              - etl
            volumeMounts:
            - mountPath: /etc/config
              name: stocker-config-volume
          volumes:
          - name: stocker-config-volume
            projected:
              sources:
              - configMap:
                  name: stocker-config-cm
              - secret:
                  name: stocker-api-secret
              - secret:
                  name: stocker-db-secret