{{- if .Values.cronJob.schedule }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Chart.Name }}-cronjob
spec:
  schedule: "{{ .Values.cronJob.schedule }}"
  jobTemplate:
    {{- include "jobSpec" . | nindent 4 }}
{{- end }}