// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package cmd

import (
	"context"
	"github.com/Finnhub-Stock-API/finnhub-go"
	"github.com/ajjensen13/gke"
	"github.com/ajjensen13/stocker/internal/extract"
	"github.com/jackc/pgx/v4"
	"time"
)

// Injectors from wire.go:

func timezone() (*time.Location, error) {
	cmdAppConfig, err := provideAppConfig()
	if err != nil {
		return nil, err
	}
	location, err := provideTimezone(cmdAppConfig)
	if err != nil {
		return nil, err
	}
	return location, nil
}

func requestStocks(ctx context.Context, lg gke.Logger) ([]finnhub.Stock, error) {
	cmdAppSecrets, err := provideAppSecrets()
	if err != nil {
		return nil, err
	}
	cmdApiAuthContext := provideApiAuthContext(ctx, cmdAppSecrets)
	defaultApiService := provideApiServiceClient()
	backOff := provideBackoff()
	cmdAppConfig, err := provideAppConfig()
	if err != nil {
		return nil, err
	}
	v, err := provideStocks(cmdApiAuthContext, lg, defaultApiService, backOff, cmdAppConfig)
	if err != nil {
		return nil, err
	}
	return v, nil
}

func requestCandles(ctx context.Context, lg gke.Logger, stock finnhub.Stock, latest latestStocks) (finnhub.StockCandles, error) {
	cmdAppSecrets, err := provideAppSecrets()
	if err != nil {
		return finnhub.StockCandles{}, err
	}
	cmdApiAuthContext := provideApiAuthContext(ctx, cmdAppSecrets)
	defaultApiService := provideApiServiceClient()
	backOff := provideBackoff()
	cmdAppConfig, err := provideAppConfig()
	if err != nil {
		return finnhub.StockCandles{}, err
	}
	cmdLatestStock := provideLatestStock(stock, latest)
	location, err := provideTimezone(cmdAppConfig)
	if err != nil {
		return finnhub.StockCandles{}, err
	}
	cmdCandleConfig := provideCandleConfig(cmdAppConfig, cmdLatestStock, location)
	stockCandles, err := provideCandles(cmdApiAuthContext, lg, defaultApiService, backOff, stock, cmdCandleConfig)
	if err != nil {
		return finnhub.StockCandles{}, err
	}
	return stockCandles, nil
}

func requestCompanyProfile(ctx context.Context, lg gke.Logger, stock finnhub.Stock) (finnhub.CompanyProfile2, error) {
	cmdAppSecrets, err := provideAppSecrets()
	if err != nil {
		return finnhub.CompanyProfile2{}, err
	}
	cmdApiAuthContext := provideApiAuthContext(ctx, cmdAppSecrets)
	defaultApiService := provideApiServiceClient()
	backOff := provideBackoff()
	companyProfile2, err := provideCompanyProfiles(cmdApiAuthContext, lg, defaultApiService, backOff, stock)
	if err != nil {
		return finnhub.CompanyProfile2{}, err
	}
	return companyProfile2, nil
}

func queryMostRecentCandles(ctx context.Context, lg gke.Logger, tx pgx.Tx) (latestStocks, error) {
	v, err := extract.LatestStocks(ctx, tx)
	if err != nil {
		return nil, err
	}
	cmdLatestStocks := provideLatestStocks(v)
	return cmdLatestStocks, nil
}

func openTx(ctx context.Context, opts pgx.TxOptions) (pgx.Tx, func(), error) {
	userinfo, err := provideDbSecrets()
	if err != nil {
		return nil, nil, err
	}
	cmdAppConfig, err := provideAppConfig()
	if err != nil {
		return nil, nil, err
	}
	pool, cleanup, err := provideDbConnPool(ctx, userinfo, cmdAppConfig)
	if err != nil {
		return nil, nil, err
	}
	conn, cleanup2, err := provideDbConn(ctx, pool)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	tx, err := provideDbTx(ctx, conn, opts)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	return tx, func() {
		cleanup2()
		cleanup()
	}, nil
}
